-- Seed leistungen content for DE and EN
INSERT INTO content (section, key, lang, value) VALUES
  -- DE
  ('leistungen', 'title',            'de', 'Unsere Leistungen'),
  ('leistungen', 'description',      'de', 'Outsourcing und holistische SAP Logistik-Optimierung'),
  ('leistungen', 'breadcrumb',       'de', 'Leistungen'),
  ('leistungen', 'outsourcingTitle', 'de', 'IT & Fachbereich Outsourcing'),
  ('leistungen', 'outsourcingDesc',  'de', 'Wir bieten IT-Outsourcing für die inhaltliche Betreuung von SAP Logistiksystemen und Prozessen an — damit Sie keine interne IT-Mannschaft aufbauen müssen und Kosten sparen.'),
  ('leistungen', 'vconsupportLabel', 'de', 'vcsupport GmbH'),
  ('leistungen', 'vconsupportTitle', 'de', 'Sorglospakete für Ihre Prozesse'),
  ('leistungen', 'download1',        'de', 'Service Beschreibung generell'),
  ('leistungen', 'download2',        'de', 'Sorglospaket Außenhandel (Intrastat)'),
  ('leistungen', 'download3',        'de', 'Sorglospaket Clean System'),
  ('leistungen', 'sapTitle',         'de', 'SAP Logistik & Optimierung'),
  ('leistungen', 'sapDesc',          'de', 'Wir unterstützen und beraten Sie beim Aufbau und der Optimierung Ihrer Logistik- und Supply Chain-Bereiche in enger Abstimmung mit Ihrem SAP-System.'),
  ('leistungen', 'schwerpunkteLabel','de', 'Schwerpunkte'),
  ('leistungen', 'competency1',      'de', 'SCM (Supply Chain Management)'),
  ('leistungen', 'competency2',      'de', 'ECR (Efficient Consumer Response)'),
  ('leistungen', 'competency3',      'de', 'CPFR (Collaborative Planning, Forecasting & Replenishment)'),
  ('leistungen', 'competency4',      'de', 'SRM (Supplier Relationship Management)'),
  ('leistungen', 'competency5',      'de', 'CRM (Customer Relationship Management)'),
  ('leistungen', 'mBaITQuote',       'de', 'Unser Verfahrensmodell'),
  ('leistungen', 'mBaITHighlight',   'de', '„merging business & it"'),
  ('leistungen', 'mBaITText',        'de', 'liegt dem gesamten Leistungsportfolio zugrunde — wir betrachten es als Ganzes und steigern damit den Projekterfolg bei reduzierten Kosten.'),
  ('leistungen', 'philosophieLink',  'de', 'Unsere Philosophie'),

  -- EN
  ('leistungen', 'title',            'en', 'Our Services'),
  ('leistungen', 'description',      'en', 'Outsourcing and holistic SAP logistics optimization'),
  ('leistungen', 'breadcrumb',       'en', 'Services'),
  ('leistungen', 'outsourcingTitle', 'en', 'IT & Specialist Outsourcing'),
  ('leistungen', 'outsourcingDesc',  'en', 'We offer IT outsourcing for the operational management of SAP logistics systems and processes — so you don''t need to build an internal IT team and can save costs.'),
  ('leistungen', 'vconsupportLabel', 'en', 'vcsupport GmbH'),
  ('leistungen', 'vconsupportTitle', 'en', 'All-inclusive packages for your processes'),
  ('leistungen', 'download1',        'en', 'General service description'),
  ('leistungen', 'download2',        'en', 'All-inclusive package foreign trade (Intrastat)'),
  ('leistungen', 'download3',        'en', 'All-inclusive package Clean System'),
  ('leistungen', 'sapTitle',         'en', 'SAP Logistics & Optimization'),
  ('leistungen', 'sapDesc',          'en', 'We support and advise you on the development and optimization of your logistics and supply chain areas in close coordination with your SAP system.'),
  ('leistungen', 'schwerpunkteLabel','en', 'Focus areas'),
  ('leistungen', 'competency1',      'en', 'SCM (Supply Chain Management)'),
  ('leistungen', 'competency2',      'en', 'ECR (Efficient Consumer Response)'),
  ('leistungen', 'competency3',      'en', 'CPFR (Collaborative Planning, Forecasting & Replenishment)'),
  ('leistungen', 'competency4',      'en', 'SRM (Supplier Relationship Management)'),
  ('leistungen', 'competency5',      'en', 'CRM (Customer Relationship Management)'),
  ('leistungen', 'mBaITQuote',       'en', 'Our methodology model'),
  ('leistungen', 'mBaITHighlight',   'en', '"merging business & it"'),
  ('leistungen', 'mBaITText',        'en', 'underpins the entire service portfolio — we view it as a whole, thereby increasing project success at reduced costs.'),
  ('leistungen', 'philosophieLink',  'en', 'Our Philosophy')
ON CONFLICT (section, key, lang) DO NOTHING;
