-- Seed unternehmen content DE + EN
INSERT INTO content (section, key, lang, value) VALUES
  -- DE
  ('unternehmen', 'title',              'de', 'Über das Unternehmen'),
  ('unternehmen', 'description',        'de', 'Ein international tätiges Beratungsnetzwerk für Ihre Logistik.'),
  ('unternehmen', 'breadcrumb',         'de', 'Unternehmen'),
  ('unternehmen', 'vconsultLabel',      'de', 'vconsult GmbH'),
  ('unternehmen', 'companyTitle',       'de', 'International tätiges Beratungsnetzwerk'),
  ('unternehmen', 'p1',                 'de', 'vconsult ist ein international tätiges Beratungsnetzwerk, das Kunden beim Aufbau und der Optimierung ihrer Unternehmenslogistik und Supply Chain in enger Verbindung mit bestehenden und neuen SAP-Systemen unterstützt. Wir sind auf Logistikberatung in strategisch-betriebswirtschaftlicher und informationstechnischer Hinsicht (vor allem SAP) spezialisiert.'),
  ('unternehmen', 'p2',                 'de', 'Zusammen mit unseren Kunden arbeiten wir Konzepte aus und setzen diese bis hin zur SAP-Software um. Professionelles Projekt- und Changemanagement runden unser ganzheitliches Beratungsportfolio ab.'),
  ('unternehmen', 'p3',                 'de', 'Das von uns entwickelte Modell'),
  ('unternehmen', 'p3Model',            'de', '„merging business & it" (mBaIT)'),
  ('unternehmen', 'p3Rest',             'de', 'wird in Projekten generell angewendet und bietet unseren Kunden eine integrierte ganzheitliche Betrachtung der Logistikprojekte — und dadurch enorme Einsparungspotentiale.'),
  ('unternehmen', 'expertTitle',        'de', 'Ein Netzwerk von Experten'),
  ('unternehmen', 'expertDesc',         'de', 'Unser Leistungsportfolio und ein Netzwerk von erfahrenen Beratern und Partnern erlaubt es, Projekte als Ganzes professionell und zuverlässig durchzuführen — im Sinne von individualisierten „Best Practice".'),
  ('unternehmen', 'sapTeamTitle',       'de', 'Unser SAP-Consulting Team'),
  ('unternehmen', 'sapTeamDesc',        'de', 'Mit einem Team aus ausgewiesenen SAP-Experten bündeln wir spezifisches Fachwissen unter der Marke'),
  ('unternehmen', 'sapTeamBrand',       'de', 'vconsult'),
  ('unternehmen', 'sapTeamRest',        'de', 'und stellen dies unseren Kunden weltweit zur Verfügung.'),
  ('unternehmen', 'philosophieTitle',   'de', 'Unsere SAP-Berater Philosophie'),
  ('unternehmen', 'philosophieSubtitle','de', 'Welche Eigenschaften muss ein SAP-Berater haben, um erfolgreich beim und mit dem Kunden agieren zu können?'),
  ('unternehmen', 'card1Title',         'de', 'Fachabteilungen verstehen'),
  ('unternehmen', 'card1Desc',          'de', 'Ein SAP-Berater muss mit Fachabteilungen sprechen können — er muss inhaltliche Kompetenz und Prozess-Know-how vorweisen können. Er muss kommunikativ sein, Anforderungen verstehen und sofort bewerten können.'),
  ('unternehmen', 'card1Feature1',      'de', 'Schnelle Bewertung von Anforderungen'),
  ('unternehmen', 'card1Feature2',      'de', 'Sofortiges und professionelles Feedback'),
  ('unternehmen', 'card2Title',         'de', 'Technische Exzellenz aus einer Hand'),
  ('unternehmen', 'card2Desc',          'de', 'Es ist wichtig, dass ein SAP-Berater nicht nur das Konfigurieren (Customizing) der SAP-Software beherrscht, sondern auch Erweiterungen selbständig und aus einer Hand umsetzen kann.'),
  ('unternehmen', 'card2Highlight',     'de', 'Für vconsult ist somit wichtig, dass jeder SAP-Berater diese Skills beherrscht — nur dann ist eine effiziente Arbeitsweise garantiert.'),
  ('unternehmen', 'ctaText',            'de', '25 zufriedene Kunden vertrauen auf unsere Expertise — lernen Sie unsere Kunden und Partner kennen.'),
  ('unternehmen', 'ctaKunden',          'de', 'Kunden kennenlernen'),
  ('unternehmen', 'ctaKontakt',         'de', 'Kontakt aufnehmen'),

  -- EN
  ('unternehmen', 'title',              'en', 'About the Company'),
  ('unternehmen', 'description',        'en', 'An internationally active consulting network for your logistics.'),
  ('unternehmen', 'breadcrumb',         'en', 'About us'),
  ('unternehmen', 'vconsultLabel',      'en', 'vconsult GmbH'),
  ('unternehmen', 'companyTitle',       'en', 'Internationally active consulting network'),
  ('unternehmen', 'p1',                 'en', 'vconsult is an internationally active consulting network that supports clients in building and optimizing their corporate logistics and supply chain in close connection with existing and new SAP systems. We specialize in logistics consulting from a strategic business and information technology perspective (especially SAP).'),
  ('unternehmen', 'p2',                 'en', 'Together with our clients, we develop concepts and implement them all the way to SAP software. Professional project and change management rounds off our holistic consulting portfolio.'),
  ('unternehmen', 'p3',                 'en', 'The model we developed,'),
  ('unternehmen', 'p3Model',            'en', '"merging business & it" (mBaIT)'),
  ('unternehmen', 'p3Rest',             'en', 'is generally applied in projects and offers our clients an integrated holistic view of logistics projects — and thereby enormous savings potential.'),
  ('unternehmen', 'expertTitle',        'en', 'A Network of Experts'),
  ('unternehmen', 'expertDesc',         'en', 'Our service portfolio and a network of experienced consultants and partners allows projects to be carried out professionally and reliably as a whole — in the spirit of individualized "Best Practice".'),
  ('unternehmen', 'sapTeamTitle',       'en', 'Our SAP Consulting Team'),
  ('unternehmen', 'sapTeamDesc',        'en', 'With a team of proven SAP experts, we pool specific expertise under the brand'),
  ('unternehmen', 'sapTeamBrand',       'en', 'vconsult'),
  ('unternehmen', 'sapTeamRest',        'en', 'and make it available to our clients worldwide.'),
  ('unternehmen', 'philosophieTitle',   'en', 'Our SAP Consultant Philosophy'),
  ('unternehmen', 'philosophieSubtitle','en', 'What qualities must an SAP consultant have to act successfully with and for the client?'),
  ('unternehmen', 'card1Title',         'en', 'Understanding Specialist Departments'),
  ('unternehmen', 'card1Desc',          'en', 'An SAP consultant must be able to talk to specialist departments — they must demonstrate content competence and process know-how. They must be communicative, understand requirements, and be able to evaluate them immediately.'),
  ('unternehmen', 'card1Feature1',      'en', 'Rapid assessment of requirements'),
  ('unternehmen', 'card1Feature2',      'en', 'Immediate and professional feedback'),
  ('unternehmen', 'card2Title',         'en', 'Technical Excellence from a Single Source'),
  ('unternehmen', 'card2Desc',          'en', 'It is important that an SAP consultant not only masters the configuration (customizing) of SAP software, but can also implement extensions independently and from a single source.'),
  ('unternehmen', 'card2Highlight',     'en', 'It is therefore important for vconsult that every SAP consultant masters these skills — only then is an efficient way of working guaranteed.'),
  ('unternehmen', 'ctaText',            'en', '25 satisfied clients trust our expertise — get to know our clients and partners.'),
  ('unternehmen', 'ctaKunden',          'en', 'Meet our clients'),
  ('unternehmen', 'ctaKontakt',         'en', 'Get in touch')
ON CONFLICT (section, key, lang) DO NOTHING;

-- Seed kontakt content DE + EN
INSERT INTO content (section, key, lang, value) VALUES
  -- DE
  ('kontakt', 'title',               'de', 'Kontaktieren Sie uns'),
  ('kontakt', 'description',         'de', 'Haben Sie Fragen, benötigen Sie Unterstützung? Bitte kontaktieren Sie uns unverbindlich.'),
  ('kontakt', 'breadcrumb',          'de', 'Kontakt'),
  ('kontakt', 'heading',             'de', 'Setzen Sie sich mit uns in Verbindung.'),
  ('kontakt', 'subheading',          'de', 'Wir sind von Montag bis Freitag immer online für Sie verfügbar.'),
  ('kontakt', 'addressTitle',        'de', 'vconsult GmbH Adresse'),
  ('kontakt', 'addressLine1',        'de', 'AirportCity Space, Towerstraße 3'),
  ('kontakt', 'addressLine2',        'de', '1300 Wien-Flughafen, Österreich'),
  ('kontakt', 'phoneTitle',          'de', 'Telefon'),
  ('kontakt', 'emailTitle',          'de', 'Email'),
  ('kontakt', 'formTitle',           'de', 'Schreiben Sie eine Nachricht'),
  ('kontakt', 'firstNameLabel',      'de', 'Vorname'),
  ('kontakt', 'firstNamePlaceholder','de', 'Max'),
  ('kontakt', 'lastNameLabel',       'de', 'Nachname'),
  ('kontakt', 'lastNamePlaceholder', 'de', 'Mustermann'),
  ('kontakt', 'emailLabel',          'de', 'E-Mail Adresse'),
  ('kontakt', 'emailPlaceholder',    'de', 'max@unternehmen.com'),
  ('kontakt', 'messageLabel',        'de', 'Ihre Nachricht'),
  ('kontakt', 'messagePlaceholder',  'de', 'Wie können wir Ihnen helfen?'),
  ('kontakt', 'submitBtn',           'de', 'Nachricht senden'),

  -- EN
  ('kontakt', 'title',               'en', 'Contact us'),
  ('kontakt', 'description',         'en', 'Do you have questions or need support? Please contact us without obligation.'),
  ('kontakt', 'breadcrumb',          'en', 'Contact'),
  ('kontakt', 'heading',             'en', 'Get in touch with us.'),
  ('kontakt', 'subheading',          'en', 'We are available for you online from Monday to Friday.'),
  ('kontakt', 'addressTitle',        'en', 'vconsult GmbH Address'),
  ('kontakt', 'addressLine1',        'en', 'AirportCity Space, Towerstraße 3'),
  ('kontakt', 'addressLine2',        'en', '1300 Vienna Airport, Austria'),
  ('kontakt', 'phoneTitle',          'en', 'Phone'),
  ('kontakt', 'emailTitle',          'en', 'Email'),
  ('kontakt', 'formTitle',           'en', 'Send us a message'),
  ('kontakt', 'firstNameLabel',      'en', 'First Name'),
  ('kontakt', 'firstNamePlaceholder','en', 'John'),
  ('kontakt', 'lastNameLabel',       'en', 'Last Name'),
  ('kontakt', 'lastNamePlaceholder', 'en', 'Smith'),
  ('kontakt', 'emailLabel',          'en', 'Email Address'),
  ('kontakt', 'emailPlaceholder',    'en', 'john@company.com'),
  ('kontakt', 'messageLabel',        'en', 'Your Message'),
  ('kontakt', 'messagePlaceholder',  'en', 'How can we help you?'),
  ('kontakt', 'submitBtn',           'en', 'Send message')
ON CONFLICT (section, key, lang) DO NOTHING;
